[Greeter]
theme-name=GNU-Darwin Aqua
icon-theme-name=GNU-Darwin Aqua icons
cursor-theme-name=GNU-Darwin Aqua cursors
cursor-theme-size=24
background=/usr/share/backgrounds/gnu-darwin-aqua/wallpaper.png
background-color=#265098
draw-user-backgrounds=false
font-name=Liberation Sans 11
