# Macintosh Soft — appearance only
font_family Hack
font_size 11.0
background_opacity 1.0
background #293238
foreground #EBE9E1
cursor #D4C581
cursor_text_color #293238
selection_background #356262
selection_foreground #FBF8F1
active_tab_background #EBE9E1
active_tab_foreground #293238
inactive_tab_background #293238
inactive_tab_foreground #A8B3AE
url_color #8CAEBE
color0 #949F9A
color1 #C895A3
color2 #99B79C
color3 #D4C581
color4 #8CAEBE
color5 #A9A3BF
color6 #9DC6C3
color7 #EBE9E1
color8 #A8B3AE
color9 #E4ADB6
color10 #ADC8AF
color11 #E5D89F
color12 #ABC8D5
color13 #C2BCD4
color14 #B8DAD5
color15 #FBF8F1
