[Greeter]
theme-name=GNU-Darwin Workstation
icon-theme-name=GNU-Darwin Workstation icons
cursor-theme-name=GNU-Darwin Workstation cursors
cursor-theme-size=24
background=/usr/share/backgrounds/gnu-darwin-workstation/wallpaper.png
background-color=#000000
draw-user-backgrounds=false
font-name=Liberation Sans 10
