# Ocean-Silk-Glass — appearance only
font_family Hack
font_size 11.0
background_opacity 1.0
background #304957
foreground #E9EBE6
cursor #D6C6A0
cursor_text_color #304957
selection_background #354D64
selection_foreground #E9EBE6
active_tab_background #E9EBE6
active_tab_foreground #304957
inactive_tab_background #304957
inactive_tab_foreground #B2C4C9
url_color #ADC4D2
color0 #8CA1AA
color1 #D5A4A4
color2 #AFC3B1
color3 #D6C6A0
color4 #ADC4D2
color5 #C0B8D0
color6 #A7CFD0
color7 #E9EBE6
color8 #B2C4C9
color9 #E4BCB8
color10 #C2D7C0
color11 #E9D9B8
color12 #C3D8E5
color13 #D6CCE1
color14 #C5E5E2
color15 #F3F5EF
